// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvbR_okMeUhyoMmRUJs2_sU6sbrE0FpIQ',
    appId: '1:585592659875:android:6aeeb0fc592987d5404416',
    messagingSenderId: '585592659875',
    projectId: 'boomerang-beta1',
    databaseURL: 'https://boomerang-beta1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'boomerang-beta1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzrpamE9GOV--qQd3tGQ18P423UaiV-gQ',
    appId: '1:585592659875:ios:264b47dfb09adede404416',
    messagingSenderId: '585592659875',
    projectId: 'boomerang-beta1',
    databaseURL: 'https://boomerang-beta1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'boomerang-beta1.appspot.com',
    androidClientId: '585592659875-52j6t0uv4t3q7ujhfmdve8cs6t45i7pf.apps.googleusercontent.com',
    iosClientId: '585592659875-7ke6kd0u581rrt5mlr9ml0vlqi609ri1.apps.googleusercontent.com',
    iosBundleId: 'com.boomerang-delivery.pos-terminal',
  );
}
