// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVgaWeUMS9Zh7MniqksSqGy7KVHn_-EE4',
    appId: '1:163312496929:android:64d7fff435168bc5bf4e60',
    messagingSenderId: '163312496929',
    projectId: 'boomerang-c2222',
    storageBucket: 'boomerang-c2222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPD4uKHY9Q6Aam2vouluAvC3RXQacatzY',
    appId: '1:163312496929:ios:886eeabc21f4dbb6bf4e60',
    messagingSenderId: '163312496929',
    projectId: 'boomerang-c2222',
    storageBucket: 'boomerang-c2222.appspot.com',
    androidClientId: '163312496929-6boic2t04e7std564bqi3tdf4f7ms2gn.apps.googleusercontent.com',
    iosClientId: '163312496929-paja8b534stvcvqkvv5d4licn38jg8rd.apps.googleusercontent.com',
    iosBundleId: 'com.boomerang-delivery.pos-terminal',
  );
}
